language: rust
rust:
  - stable

cache:
  directories:
    - target

os:
  - osx

script:
  - cargo build --release

deploy:
  provider: releases
  api_key:
    secure: bEDA8HUNOFolMBLi5y/gnWez8Z7u+DugOImdxgGP5C7SIWK45EgokOUsjWES5tyuP6oFbW3GPicCK3lgVU22C3EL8FYIUzy7bM7bgbVWFWkIUJYj60EPvncZzKDnlcQCEjwIeYVtN/wh31W4If7A7NYBL5/3/VlAA0nI48xM+gFEp/hGSk08km+Tu7i/yHlDzTRwKThpLZgG0Lj1Z6LOIYJXznhNMUSVULW1wJdZ5zzzajHd/9Ff+gZVAwaYiKE7qY7hO7xfq6LvV5atY+DSwxCaQ6skF1YH1vUYU/rM7o1gGpkxYRziWedQzfO1gGB2iSjUEbe8qfyyO8CoIHR8TUdb99Ymmhi6Lg/IlQMtHNFxNBxkhhbkF2Xn5MREUpWlyVFf7VvsrvEfxIBe1MIhto9iK2Rega6Y1Jh7fVaRbO0L8w9tW4bSteMJPizdffdU3vVq5U6N4c120nnZIbido5gGpPKkGl44/Lzx8riXZ08cHRQUEFHawJm9l6Kh52zxp6mYhBM1MmU4+LnG12d/EC4/puySu+70tpWniNNcsZ83bRm/g/L4zkc4HF/4OHj19YsaWDT4qL4Y5UaTeh39/S2O3j/Ntjdw/anSpkzdX5YvvX35cbpjjUk8OnXthNAvH3WJzTniKEx2h4JDF7rn6hJgBq71Iso5FiHNJ2JvyLM=
  file:
    - target/release/awscredx
  skip_cleanup: true
  on:
    tags: true
