# This file is generated by @bin@.
# Do not edit.

set -x AWSCREDX_SCRIPT_VERSION "@version@"

function assume
  set -l output ("@bin@" assume $argv)
  set -l s $status
  if test $s -eq 0
    eval "$output"
  else
    return $s
  end
end
