# This file is generated by @bin@.
# Do not edit.

export AWSCREDX_SCRIPT_VERSION="@version@"
function assume {
  out=$("@bin@" assume "$@")
  s=$?
  if [[ $s == 0 ]]; then
    $out
  else
    return $s
  fi
}
