# This file is generated by @bin@.
# Do not edit.

set -x AWSCREDX_SCRIPT_VERSION "@version@"
functions -q _original_fish_prompt
if test $status -ne 0
  functions -c fish_prompt _original_fish_prompt
end

if test -e $HOME/.config/fish/functions/fish_prompt.fish
  cat $HOME/.config/fish/functions/fish_prompt.fish | grep AWS_PROFILE > /dev/null
  if test $status -eq 0
    set _original_prompt_has_aws_profile 1
  end
end

function assume
  set -l output ("@bin@" assume $argv)
  set -l s $status
  switch $s
    case 0
      eval "$output"
      if test -z "$_original_prompt_has_aws_profile"
        function fish_prompt
          set -l old_status $status

          echo -n "["
          set_color brmagenta
          echo -n $AWS_PROFILE
          set_color normal
          echo -n "] "

          echo -n "exit $old_status" | .
          _original_fish_prompt
        end
      end
    case 50
      "@bin@" init
      source $HOME/.local/share/awscredx/script.fish
      assume $argv
    case '*'
      return $s
  end
end
