# This file is generated by @bin@.
# Do not edit.

export AWSCREDX_SCRIPT_VERSION="@version@"
if [ -z "$_ORIGINAL_PS1" ]; then
  _ORIGINAL_PS1="${PS1:-}"
fi

function assume {
  out=$("@bin@" assume "$@")
  s=$?
  case $s in
    0)
      eval $out
      if [[ $SHELL =~ zsh ]]; then
        PS1=$'[\e[1;35m'$AWS_PROFILE$'\e[0m] '${_ORIGINAL_PS1:-}
      else
        PS1="[\e[1;35m\$AWS_PROFILE\e[0m] ${_ORIGINAL_PS1:-}"
      fi
      ;;
    50)
      "@bin@" init
      source $HOME/.local/share/awscredx/script.sh
      assume "$@"
      ;;
    *)
      return $s
      ;;
  esac
}
